import { User, Client, Brief, Task, Ad, UserRole } from '@/types';

export const mockUsers: User[] = [
  { id: '1', name: 'Alex Morgan', email: 'alex@agency.com', role: 'admin', avatar: '' },
  { id: '2', name: 'Sarah Chen', email: 'sarah@agency.com', role: 'dm_manager', avatar: '' },
  { id: '3', name: 'Mike Johnson', email: 'mike@agency.com', role: 'copywriter', avatar: '' },
  { id: '4', name: 'Emily Davis', email: 'emily@agency.com', role: 'copy_qc', avatar: '' },
  { id: '5', name: 'James Wilson', email: 'james@agency.com', role: 'designer', avatar: '' },
  { id: '6', name: 'Lisa Park', email: 'lisa@agency.com', role: 'design_qc', avatar: '' },
  { id: '7', name: 'David Brown', email: 'david@agency.com', role: 'client_coordinator', avatar: '' },
  { id: '8', name: 'Rachel Green', email: 'rachel@agency.com', role: 'dm_team_lead', avatar: '' },
];

export const mockClients: Client[] = [
  { id: '1', name: 'TechStart Inc', industry: 'Technology', monthlyBudget: 50000, createdAt: new Date('2024-01-15') },
  { id: '2', name: 'Fashion Forward', industry: 'Retail', monthlyBudget: 35000, createdAt: new Date('2024-02-01') },
  { id: '3', name: 'HealthPlus', industry: 'Healthcare', monthlyBudget: 45000, createdAt: new Date('2024-01-20') },
  { id: '4', name: 'EcoLiving', industry: 'Sustainability', monthlyBudget: 25000, createdAt: new Date('2024-03-10') },
  { id: '5', name: 'FinanceHub', industry: 'Finance', monthlyBudget: 60000, createdAt: new Date('2024-02-15') },
];

export const mockBriefs: Brief[] = [
  {
    id: '1',
    clientId: '1',
    title: 'Q1 Product Launch Campaign',
    objective: 'Increase brand awareness for new product line',
    targetAudience: 'Tech enthusiasts, 25-45 years',
    platform: ['facebook', 'instagram', 'linkedin'],
    budget: 15000,
    priority: 'high',
    deadline: new Date('2024-12-20'),
    createdAt: new Date('2024-12-01'),
    createdBy: '2',
    status: 'in_progress',
  },
  {
    id: '2',
    clientId: '2',
    title: 'Winter Collection Showcase',
    objective: 'Drive sales for winter collection',
    targetAudience: 'Fashion-conscious women, 18-35 years',
    platform: ['instagram', 'facebook'],
    budget: 10000,
    priority: 'critical',
    deadline: new Date('2024-12-15'),
    createdAt: new Date('2024-12-02'),
    createdBy: '2',
    status: 'review',
  },
  {
    id: '3',
    clientId: '3',
    title: 'Health Awareness Campaign',
    objective: 'Promote preventive health checkups',
    targetAudience: 'Adults 30-60 years',
    platform: ['facebook', 'google_ads'],
    budget: 12000,
    priority: 'normal',
    deadline: new Date('2024-12-25'),
    createdAt: new Date('2024-12-03'),
    createdBy: '2',
    status: 'pending',
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    briefId: '1',
    assigneeId: '3',
    type: 'copy',
    status: 'approved',
    priority: 'high',
    deadline: new Date('2024-12-10'),
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-08'),
  },
  {
    id: '2',
    briefId: '1',
    assigneeId: '5',
    type: 'design',
    status: 'in_progress',
    priority: 'high',
    deadline: new Date('2024-12-12'),
    createdAt: new Date('2024-12-08'),
    updatedAt: new Date('2024-12-09'),
  },
  {
    id: '3',
    briefId: '2',
    assigneeId: '3',
    type: 'copy',
    status: 'review',
    priority: 'critical',
    deadline: new Date('2024-12-08'),
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-07'),
  },
  {
    id: '4',
    briefId: '3',
    assigneeId: '3',
    type: 'copy',
    status: 'pending',
    priority: 'normal',
    deadline: new Date('2024-12-15'),
    createdAt: new Date('2024-12-03'),
    updatedAt: new Date('2024-12-03'),
  },
];

export const mockAds: Ad[] = [
  {
    id: '1',
    briefId: '1',
    clientId: '1',
    type: 'awareness',
    platform: 'facebook',
    budget: 5000,
    spent: 2350,
    leads: 0,
    reach: 125000,
    ctr: 2.4,
    status: 'active',
    startDate: new Date('2024-12-01'),
  },
  {
    id: '2',
    briefId: '1',
    clientId: '1',
    type: 'lead_generation',
    platform: 'instagram',
    budget: 10000,
    spent: 4200,
    leads: 156,
    reach: 85000,
    ctr: 3.2,
    status: 'active',
    startDate: new Date('2024-12-01'),
  },
  {
    id: '3',
    briefId: '2',
    clientId: '2',
    type: 'awareness',
    platform: 'instagram',
    budget: 6000,
    spent: 5800,
    leads: 0,
    reach: 200000,
    ctr: 4.1,
    status: 'active',
    startDate: new Date('2024-12-05'),
  },
];

export const roleLabels: Record<UserRole, string> = {
  admin: 'Admin',
  dm_manager: 'DM Manager',
  copywriter: 'Copywriter',
  copy_qc: 'Copy QC',
  designer: 'Designer',
  design_qc: 'Design QC',
  client_coordinator: 'Client Coordinator',
  dm_team_lead: 'DM Team Lead',
};

export const statusColors: Record<string, string> = {
  draft: 'status-draft',
  pending: 'status-pending',
  in_progress: 'status-in-progress',
  review: 'status-review',
  approved: 'status-approved',
  rejected: 'status-rejected',
  client_review: 'status-review',
  published: 'status-approved',
};

export const priorityColors: Record<string, string> = {
  low: 'priority-low',
  normal: 'priority-normal',
  high: 'priority-high',
  critical: 'priority-critical',
};
